name: bloom_beauty
description: "A beauty products ecommerce Flutter app."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # HTTP and API
  http: ^1.1.0
  dio: ^5.3.2

  # State Management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9

  # Local Storage
  shared_preferences: ^2.2.2
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0

  # UI and Animations
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  # smooth_page_indicator: ^1.1.0
  # flutter_staggered_grid_view: ^0.7.0

  # Navigation
  go_router: ^12.1.3

  # Forms and Validation
  email_validator: ^2.1.17

  # Image Handling - Temporarily removed to fix Android SDK issue
  # image_picker: ^0.8.9

  # Internationalization
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  # Utils
  uuid: ^4.2.1
  equatable: ^2.0.5
  url_launcher: ^6.2.2

  # Icons and Fonts
  cupertino_icons: ^1.0.6

  # UI Components
  flutter_native_splash: ^2.3.6
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # hive_generator: ^2.0.1
  # build_runner: ^2.4.7

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/

  # Fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
