# Generated by Django 4.2.7 on 2025-06-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_productattribute_productattributevalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='beauty_points',
            field=models.PositiveIntegerField(default=0, help_text='Beauty points earned when purchasing this product'),
        ),
    ]
