# Generated by Django 4.2.7 on 2025-06-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_platformstats_review_productrating_reviewhelpfulness_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlatformStats',
        ),
        migrations.AlterUniqueTogether(
            name='reviewhelpfulness',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reviewhelpfulness',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewhelpfulness',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='productrating',
            name='products_pr_bayesia_e0a6f5_idx',
        ),
        migrations.RemoveIndex(
            model_name='productrating',
            name='products_pr_confide_992672_idx',
        ),
        migrations.RenameField(
            model_name='productrating',
            old_name='bayesian_average',
            new_name='average_rating',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='confidence_level',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='raw_average',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='time_weighted_average',
        ),
        migrations.RemoveField(
            model_name='review',
            name='helpful_count',
        ),
        migrations.RemoveField(
            model_name='review',
            name='total_votes',
        ),
        migrations.AddIndex(
            model_name='productrating',
            index=models.Index(fields=['-average_rating'], name='products_pr_average_9836d1_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating', '-created_at'], name='products_re_rating_45c58b_idx'),
        ),
        migrations.DeleteModel(
            name='ReviewHelpfulness',
        ),
    ]
