# Generated by Django 5.2.1 on 2025-06-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_complex_rating_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
