# Generated by Django 5.2.1 on 2025-06-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_slug_weight_dimensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
