# Generated by Django 4.2.18 on 2025-05-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash On Delivery')], default='cash_on_delivery', max_length=20),
        ),
    ]
