# Generated by Django 5.2.1 on 2025-06-21 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name for the category (e.g., 'EYES', 'FACE')", max_length=50, unique=True)),
                ('value', models.CharField(help_text="Internal value for filtering (e.g., 'eyes', 'face')", max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Value must be lowercase letters and underscores only', regex='^[a-z_]+$')])),
                ('icon', models.CharField(blank=True, help_text='Material Icon name (optional)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description for this category')),
                ('keywords', models.TextField(help_text="Comma-separated keywords for product filtering (e.g., 'eye,mascara,shadow,liner')")),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is visible in the navigation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Navigation Category',
                'verbose_name_plural': 'Navigation Categories',
                'db_table': 'navigation_categories',
                'ordering': ['order', 'name'],
            },
        ),
    ]
