# Generated by Django 4.2.7 on 2025-06-19 16:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_remove_complex_rating_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='celebrities/')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('bio', models.TextField(blank=True, help_text='Celebrity biography/description', null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL', null=True, validators=[django.core.validators.URLValidator()])),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook profile URL', null=True, validators=[django.core.validators.URLValidator()])),
                ('snapchat_url', models.URLField(blank=True, help_text='Snapchat profile URL', null=True, validators=[django.core.validators.URLValidator()])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Celebrities',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='CelebrityProductPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial', models.TextField(blank=True, help_text="Celebrity's testimonial about this product", null=True)),
                ('promotion_type', models.CharField(choices=[('general', 'General Promotion'), ('morning_routine', 'Morning Routine'), ('evening_routine', 'Evening Routine'), ('special_pick', 'Special Pick')], default='general', max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='Is this a featured promotion?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_promotions', to='celebrities.celebrity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celebrity_promotions', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CelebrityMorningRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order in the morning routine (1, 2, 3, etc.)')),
                ('description', models.TextField(blank=True, help_text='How the celebrity uses this product in their morning routine', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morning_routine_items', to='celebrities.celebrity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celebrity_morning_routines', to='products.product')),
            ],
            options={
                'ordering': ['celebrity', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CelebrityEveningRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order in the evening routine (1, 2, 3, etc.)')),
                ('description', models.TextField(blank=True, help_text='How the celebrity uses this product in their evening routine', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evening_routine_items', to='celebrities.celebrity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celebrity_evening_routines', to='products.product')),
            ],
            options={
                'ordering': ['celebrity', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='celebrity',
            index=models.Index(fields=['first_name', 'last_name'], name='celebrities_first_n_a5f08c_idx'),
        ),
        migrations.AddIndex(
            model_name='celebrity',
            index=models.Index(fields=['is_active'], name='celebrities_is_acti_b67cec_idx'),
        ),
        migrations.AddIndex(
            model_name='celebrityproductpromotion',
            index=models.Index(fields=['celebrity', 'promotion_type'], name='celebrities_celebri_f7f2ec_idx'),
        ),
        migrations.AddIndex(
            model_name='celebrityproductpromotion',
            index=models.Index(fields=['product', 'is_featured'], name='celebrities_product_6bff58_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='celebrityproductpromotion',
            unique_together={('celebrity', 'product', 'promotion_type')},
        ),
        migrations.AddIndex(
            model_name='celebritymorningroutine',
            index=models.Index(fields=['celebrity', 'order'], name='celebrities_celebri_9f8638_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='celebritymorningroutine',
            unique_together={('celebrity', 'product')},
        ),
        migrations.AddIndex(
            model_name='celebrityeveningroutine',
            index=models.Index(fields=['celebrity', 'order'], name='celebrities_celebri_b6fc30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='celebrityeveningroutine',
            unique_together={('celebrity', 'product')},
        ),
    ]
