# Generated by Django 4.2.7 on 2025-06-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrity',
            name='slug',
        ),
    ]
