# Generated by Django 5.2.1 on 2025-05-28 18:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.TextField()),
                ('query_params', models.TextField(blank=True, null=True)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('response_status', models.PositiveIntegerField()),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('response_size', models.PositiveIntegerField(default=0)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referer', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_time', models.FloatField(help_text='Response time in milliseconds')),
                ('view_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_api_request', models.BooleanField(default=False)),
                ('is_admin_request', models.BooleanField(default=False)),
                ('is_error', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='request_log_timesta_efa357_idx'), models.Index(fields=['method'], name='request_log_method_57560a_idx'), models.Index(fields=['response_status'], name='request_log_respons_034c5e_idx'), models.Index(fields=['user'], name='request_log_user_id_766ae3_idx'), models.Index(fields=['is_api_request'], name='request_log_is_api__68b66c_idx'), models.Index(fields=['is_error'], name='request_log_is_erro_9b555a_idx')],
            },
        ),
    ]
