# Generated by Django 4.2.18 on 2025-05-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_address_user_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marketing_emails',
            field=models.BooleanField(default=True, help_text='Receive marketing emails and promotions'),
        ),
        migrations.AddField(
            model_name='user',
            name='order_updates_notifications',
            field=models.BooleanField(default=True, help_text='Receive notifications about order status changes'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AED', 'UAE Dirham')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('fr', 'French')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='product_recommendations',
            field=models.BooleanField(default=True, help_text='Receive product recommendations based on browsing history'),
        ),
        migrations.AddField(
            model_name='user',
            name='wishlist_alerts',
            field=models.BooleanField(default=True, help_text='Receive alerts when wishlist items go on sale'),
        ),
    ]
