# Generated by Django 4.2.16 on 2025-06-21 15:53

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_marketing_emails_and_more'),
    ]

    operations = [
        # First, populate phone_number for existing users who don't have one
        migrations.RunSQL(
            "UPDATE users_user SET phone_number = '+1000000000' || id WHERE phone_number IS NULL OR phone_number = '';",
            reverse_sql="UPDATE users_user SET phone_number = NULL WHERE phone_number LIKE '+1000000000%';"
        ),
        
        # Make phone_number unique and required
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(
                help_text='Phone number for authentication', 
                max_length=17, 
                unique=True,
                validators=[django.core.validators.RegexValidator(
                    message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", 
                    regex='^\\+?1?\\d{9,15}$'
                )]
            ),
        ),
        
        # Make email optional
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        
        # Make username optional
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                blank=True, 
                help_text='Optional. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', 
                max_length=150, 
                null=True, 
                verbose_name='username'
            ),
        ),
    ]
